# Generated by Django 4.1 on 2022-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('cabin_id', models.AutoField(primary_key=True, serialize=False)),
                ('cabin_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cabin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cookingcabin',
            fields=[
                ('cookingcabin_id', models.AutoField(primary_key=True, serialize=False)),
                ('cookingcabin_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CookingCabin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('item_price', models.IntegerField()),
                ('item_category', models.TextField()),
                ('item_type', models.TextField()),
            ],
            options={
                'db_table': 'Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('waiting_time', models.TextField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('total_amount', models.TextField()),
                ('cabin_id', models.IntegerField()),
                ('cookingcabin_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('amount', models.TextField()),
                ('trans_status', models.TextField(blank=True, null=True)),
                ('cabin_id', models.IntegerField()),
                ('cookingcabin_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Transaction',
                'managed': False,
            },
        ),
    ]
