# Generated by Django 4.1.2 on 2023-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('waiting_time', models.TextField(blank=True, null=True)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('total_amount', models.TextField()),
                ('cabin_id', models.IntegerField()),
                ('cookingcabin_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
